name: FriendlyElec R2S
#

env:
  SSH_ACTIONS:  false
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on:
  push:
    paths:
      - 'FriendlyElec-r2s.yml'
  watch:
    types: started
  schedule:
    - cron: '0 12 * * 5'
  release:
    types: [published]
  
jobs:

  build:
    timeout-minutes: 720
    runs-on: ubuntu-18.04
    #runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Initialize Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
          sudo docker image prune -a -f
          sudo apt-get -y install unzip upx-ucl subversion
          sudo apt-get -y purge dotnet* ghc* google* llvm* mysql* php* zulu* firefox hhvm
          sudo apt-get -y autoremove --purge          
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash
          
      - name: Install Repo
        run: |
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/
          
      - name: Download Source
        run: |
          rm -rf code
          mkdir code
          cd code
          repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v19.07.5 -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle
          repo sync -c --no-clone-bundle -j8
          
      - name: Clone Feeds
        run: |
          cd code/friendlywrt/
          ./scripts/feeds update -a
          
      - name: Install Feeds	
        run: |		
          cd code/friendlywrt		
          ./scripts/feeds install -a
          
      - name: Set Default Values
        run: |
          cd code/friendlywrt
          echo -e "\nBuild date:$(date +%Y-%m-%d), by dongyusen@gmail.com\n" >> package/base-files/files/etc/banner
          
          #rm -f .config*
          #cat ../../feeds-1907.conf > .config
          #cp ../../feeds-1907.conf ../configs/config_rk3328

      - name: SSH连接
        uses: DONGYUSEN/debugger-action@master
        if: env.SSH_ACTIONS == 'true'   
        
      - name: Build OpenWrt
        run: |
          cd code/
          sed -i '/feeds/d' scripts/mk-friendlywrt.sh
          sed -i 's/set -eu/set -u/' scripts/mk-friendlywrt.sh
          sed -i 's/make -j$(nproc) V=s/make -j3/' scripts/mk-friendlywrt.sh
          ./build.sh nanopi_r2s.mk
         
      - name: Fix Rootfs Owner and Group
        run: |
          sudo df -lh
          #lodev=$(sudo losetup -f)
          #echo "found unused loop dev $lodev"
          #sudo losetup -o 100663296 $lodev code/out/*.img
          ##sudo mkfs -t ext4 $lodev
          #sudo rm -rf /mnt/friendlywrt-tmp
          #sudo mkdir -p /mnt/friendlywrt-tmp
          #sudo mount $lodev /mnt/friendlywrt-tmp
          #sudo chown -R root:root /mnt/friendlywrt-tmp
          #sudo umount /mnt/friendlywrt-tmp
          #sudo losetup -d $lodev
          
      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          cp code/out/*.img.zip ./artifact/
          
          ls -lh code/out/*
          cp code/friendlywrt/.config ./artifact/config.seed.txt
          tar -czvf ./artifact/packages.tar.gz ./code/friendlywrt/bin/targets/rockchip-rk3328/generic/packages/
          
          echo "strDate=$(TZ=UTC-8 date '+%Y-%m-%d')" >> $GITHUB_ENV
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: FriendlyElec-r2s
          path: ./artifact/
          
      - name: set NOW
        run: |
          echo "::set-env name=NOW::$(date +'%Y-%m-%dT%H-%M-%S')"
          
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.8.6
        with:
          name: "FriendlyElec R2s v19.07.5 官方原版重新编译"
          tag: ${{ env.NOW }}
          #tag_name: ${{env.strDate}} 
          #commit: main
          #replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ./artifact/*.zip,./artifact/*.gz,./artifact/*.txt
          
      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        if: env.UPLOAD_RELEASE == 'true' && !cancelled()
        with:
          keep_latest: 30
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
          
      - name: Delete Artifacts
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            FriendlyElec-r2s
